### ISSUE TITLE
2) Implement a Point System (XP) to be used for unlocking items rather than individual ranks.

### ISSUE THREAD

**Issue by fihgus** [fihgus/McMurder-Issue-Tracking#8]
2) Implement a Point System (XP) to be used for unlocking items rather than individual ranks.

**Comment by fihgus** [comment]
Then what is rank going to do?

**Comment by gdahl** [comment]
Rather than promoting users to upgraded ranks (DIRT..etc), a XP (POINT) System would be preferred.  This system will be VERY Similar to the way Mineplex does theirs.

This will be a replacement to the rank system (Only people that get ranks is DONATOR for now).

The more the user plays, the larger the XP Number will get (Great way for users to reflect how much they play the game as there isn't any limit on the XP Number they can earn).

Specific XP Numbers will unlock shop items. This will be a easy way to manage, to add new weapons, accessories, etc.

As for the way XP is earned, I have not figured out how this would be calculated.  Perhaps 1.0 XP for every 20/30 games played.

**Comment by fihgus** [comment]
Rank points is already being displayed on HUD.
